# Generated by Django 2.2 on 2019-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=10, verbose_name='考试编号')),
                ('exam_type', models.CharField(max_length=128, verbose_name='考试类别')),
                ('exam_point', models.CharField(max_length=128, verbose_name='考点')),
                ('exam_time', models.CharField(max_length=128, verbose_name='考试时间')),
                ('number', models.IntegerField(verbose_name='容量')),
                ('entry_number', models.IntegerField(default=0, verbose_name='已报名数量')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点信息表',
            },
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('user_true_name', models.CharField(max_length=128, null=True, verbose_name='真实姓名')),
                ('user_id', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('user_school', models.CharField(max_length=128, verbose_name='在读学校')),
                ('user_f_score', models.IntegerField(default=0, verbose_name='四级成绩')),
                ('user_s_score', models.IntegerField(default=0, verbose_name='六级成绩')),
            ],
            options={
                'verbose_name': '用户名',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='user_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('exam_id', models.CharField(max_length=10, verbose_name='考试编号')),
                ('exam_point', models.CharField(max_length=128, verbose_name='考点')),
            ],
            options={
                'verbose_name': '用户考试信息',
                'verbose_name_plural': '用户考试信息表',
            },
        ),
    ]
